name: HCL OneTest Server - Webinar

on: workflow_dispatch

jobs:
    OTS-Action:
        runs-on: ubuntu-latest
        name: HCL OneTest Server
        steps:
         - name: Execute Test
           uses: HCL-TECH-SOFTWARE/onetest-server-action@main
           with:
            serverUrl: hcl-onetest.sbx0153.play.hclsofy.com
            offlineToken: eyJhbGciOiJIUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICI0MzM2ODdkZS1jMjZhLTQwOTctYWMzNS02MGJmZjliYmJjMzcifQ.eyJpYXQiOjE2NjU1ODQ5OTMsImp0aSI6ImU0MDE2ZDdmLTU1YWItNGE0NC1iZTU2LWMwZTk1NWYyNTJkMiIsImlzcyI6Imh0dHBzOi8vaGNsLW9uZXRlc3Quc2J4MDE1My5wbGF5LmhjbHNvZnkuY29tL2F1dGgvcmVhbG1zL3Rlc3RzZXJ2ZXIiLCJhdWQiOiJodHRwczovL2hjbC1vbmV0ZXN0LnNieDAxNTMucGxheS5oY2xzb2Z5LmNvbS9hdXRoL3JlYWxtcy90ZXN0c2VydmVyIiwic3ViIjoiZWQxNjJiMjAtZGIwNC00ZWE1LThlMzYtYmYyYWM5YzBjYTQ5IiwidHlwIjoiT2ZmbGluZSIsImF6cCI6InRlc3RzZXJ2ZXIiLCJzZXNzaW9uX3N0YXRlIjoiOGUzYWEwNWItY2E2MC00N2Y1LTgyM2UtOGEwZDExZTc4YWNkIiwic2NvcGUiOiJ0ZXN0c2VydmVyIGVtYWlsIG9mZmxpbmVfYWNjZXNzIHByb2ZpbGUiLCJzaWQiOiI4ZTNhYTA1Yi1jYTYwLTQ3ZjUtODIzZS04YTBkMTFlNzhhY2QifQ.6ApcP9oxY1MKtveQQCNTJ1tZDPGULRLImE2LceNApyA
            teamspace: "Initial Team Space"
            project: Emerald
            branch: DEV
            assetId: f518a420-90f0-4229-98a4-2090f0a229c9
